'use client';
// Prompt 355 §B — "Sherlock summary": a discreet per-document AI summary,
// shared-cache (document, content_sha256) so the second investor — or the
// same one again — gets an instant DB read, never a second Claude call for
// unchanged content (confirmed by the route's own `cached` flag).
//
// Asset slot: no pipe-smoking Sherlock illustration exists in this codebase
// yet (confirmed by search) — per the prompt's own explicit instruction not
// to block on that, this uses a plain emoji + a subtle pulse animation and
// the same "Sherlock is thinking…" copy. Swap the emoji span below for a
// real <img> the moment that asset exists; nothing else here needs to change.
import { useState } from 'react';

export function SherlockSummaryButton({ orgId, documentId }: { orgId: string; documentId: string }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ summary: string; highlights: string[] } | null>(null);
  const [error, setError] = useState('');

  async function fetchSummary() {
    setOpen(true);
    if (result || loading) return;
    setLoading(true); setError('');
    try {
      const res = await fetch('/api/portal/doc-summary', {
        method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ orgId, documentId }),
      });
      const body = await res.json();
      if (!body.ok) { setError(body.error ?? 'Could not generate a summary for this document.'); return; }
      setResult({ summary: body.summary, highlights: body.highlights ?? [] });
    } catch {
      setError('Could not generate a summary for this document.');
    } finally { setLoading(false); }
  }

  return (
    <div className="relative">
      <button onClick={fetchSummary} title="Sherlock summary"
        className="shrink-0 rounded-full border border-dashed border-gray-200 px-2 py-0.5 text-[10px] font-medium text-gray-400 hover:border-gray-400 hover:text-gray-600">
        🔎 Summary
      </button>
      {open && (
        <div className="absolute right-0 top-full z-30 mt-1.5 w-72 rounded-lg border border-gray-200 bg-white p-3 shadow-lg">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-900">Sherlock summary</span>
            <button onClick={() => setOpen(false)} className="text-xs text-gray-400 hover:text-gray-600">✕</button>
          </div>
          {loading ? (
            <div className="mt-2 flex flex-col items-center gap-1.5 py-3 text-center">
              <span className="animate-pulse text-2xl">🕵️</span>
              <p className="text-xs text-gray-500">Sherlock is thinking…</p>
            </div>
          ) : error ? (
            <p className="mt-2 text-xs text-[#B00000]">{error}</p>
          ) : result ? (
            <>
              <p className="mt-2 whitespace-pre-wrap text-xs leading-relaxed text-gray-700">{result.summary}</p>
              {result.highlights.length > 0 && (
                <ul className="mt-2 list-disc space-y-0.5 pl-4 text-xs text-gray-600">
                  {result.highlights.map((h, i) => <li key={i}>{h}</li>)}
                </ul>
              )}
              <p className="mt-2 text-[10px] text-gray-400">AI-generated by Sherlock, from this document&apos;s own content only.</p>
            </>
          ) : null}
        </div>
      )}
    </div>
  );
}
