'use client';
// Prompt 349 — Chamber 1 (private, ephemeral) + the doorway into Chamber 2
// (explicit, item-by-item share). "Get Watson support" never runs
// automatically — the investor asks for it. Every insight shown here is
// AI-generated (T&C clause 9): marked as such, and never persisted unless
// the investor explicitly shares that ONE item after seeing its exact text.
import { useState } from 'react';

interface Insight { kind: 'reading' | 'threshold_suggestion' | 'alert_reason'; text: string }

const KIND_LABEL: Record<Insight['kind'], string> = { reading: 'Reading', threshold_suggestion: 'Suggestion', alert_reason: 'Alert reason' };

export function WatsonEvaluationSupport({ orgId }: { orgId: string }) {
  const [insights, setInsights] = useState<Insight[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [sharedIdx, setSharedIdx] = useState<Set<number>>(new Set());
  const [sharingIdx, setSharingIdx] = useState<number | null>(null);
  const [confirmIdx, setConfirmIdx] = useState<number | null>(null);

  async function getSupport() {
    setLoading(true); setError(''); setInsights(null); setSharedIdx(new Set());
    try {
      const res = await fetch('/api/portal/watson/evaluation-support', {
        method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ orgId }),
      });
      const body = await res.json();
      if (!body.ok) { setError(body.error ?? 'Watson support is not available right now.'); return; }
      setInsights(body.insights ?? []);
    } catch {
      setError('Watson support is not available right now.');
    } finally { setLoading(false); }
  }

  async function share(idx: number) {
    const insight = insights?.[idx];
    if (!insight) return;
    setSharingIdx(idx);
    try {
      const res = await fetch('/api/portal/watson/share', {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ orgId, kind: insight.kind, text: insight.text }),
      });
      const body = await res.json();
      if (body.ok) setSharedIdx((prev) => new Set(prev).add(idx));
    } finally { setSharingIdx(null); setConfirmIdx(null); }
  }

  return (
    <div className="rounded-lg border border-cyan-100 bg-cyan-50/40 p-3">
      <div className="flex items-center justify-between">
        <span className="text-xs font-medium text-[#0E7490]">Watson</span>
        <button onClick={getSupport} disabled={loading}
          className="rounded-lg border border-cyan-300 bg-white px-2.5 py-1 text-xs font-medium text-[#0E7490] hover:bg-cyan-50 disabled:opacity-50">
          {loading ? 'Thinking…' : 'Get Watson support'}
        </button>
      </div>
      {error && <p className="mt-2 text-xs text-red-600">{error}</p>}
      {insights && insights.length === 0 && <p className="mt-2 text-xs text-gray-500">Nothing notable to point out right now.</p>}
      {insights && insights.length > 0 && (
        <ul className="mt-2 space-y-2">
          {insights.map((ins, idx) => (
            <li key={idx} className="rounded-lg bg-white px-3 py-2 text-xs shadow-sm">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <span className="rounded-full bg-gray-100 px-1.5 py-0.5 text-[10px] text-gray-500">{KIND_LABEL[ins.kind]}</span>
                  <p className="mt-1 text-gray-700">{ins.text}</p>
                  <p className="mt-1 text-[10px] text-gray-400">AI-generated by Watson — private to you unless you share it.</p>
                </div>
                {sharedIdx.has(idx) ? (
                  <span className="shrink-0 text-[10px] font-medium text-emerald-600">Shared with founder</span>
                ) : confirmIdx === idx ? (
                  <div className="shrink-0 text-right">
                    <p className="mb-1 text-[10px] text-gray-500">Share this exact text with the founder, identified as you?</p>
                    <button onClick={() => share(idx)} disabled={sharingIdx === idx}
                      className="rounded-lg bg-[#0E7490] px-2 py-1 text-[10px] font-medium text-white disabled:opacity-50">
                      {sharingIdx === idx ? 'Sharing…' : 'Confirm share'}
                    </button>
                    <button onClick={() => setConfirmIdx(null)} className="ml-1 text-[10px] text-gray-400 hover:underline">Cancel</button>
                  </div>
                ) : (
                  <button onClick={() => setConfirmIdx(idx)} className="shrink-0 text-[10px] font-medium text-[#0E7490] hover:underline">
                    Share with founder
                  </button>
                )}
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
