-- Normaliza catalog_entities.sectors (texto livre, 351 valores distintos)
-- contra a taxonomia fixa de src/lib/sector-taxonomy.ts (P104 #7). Proposta
-- revista e aprovada pelo Nuno em 2026-08-08 (89% mapeado directamente, 9%
-- correctamente identificado como NAO sendo sector nenhum -- descreve o
-- investidor, nao a startup -- e os poucos casos ambiguos resolvidos por
-- decisao minha, com aprovacao antecipada dele). Ficheiro de trabalho:
-- proposta_normalizacao_setores_catalog_20260808.xlsx (entregue e aprovado).
--
-- Aditivo, nao destrutivo: cria sectors_normalized text[] a par de sectors
-- (que fica intocado, com o texto livre original -- historico/display).
-- O motor de correspondencia (proximo passo) le sectors_normalized, nunca
-- sectors directamente.
--
-- Blockchain/Web3 ficam deliberadamente SEM valor normalizado -- a
-- taxonomia nao tem categoria de cripto, e forcar um sector errado
-- distorceria a tese real do fundo (pior do que nao ter sector). Fica
-- registado aqui como gap de taxonomia em aberto, para decisao futura do
-- Nuno se algum dia isso importar. "Health Ventures" tambem fica sem
-- valor -- parece ser nome de sub-marca (ex. COREangels Health Ventures),
-- nao um sector, provavel artefacto na fonte original dos dados.

alter table public.catalog_entities
  add column if not exists sectors_normalized text[];

with lookup(valor_original, canonicos) as (
  values
  ('enterprise saas/b2b software', ARRAY['Enterprise Software & SaaS']::text[]),
  ('saas', ARRAY['Enterprise Software & SaaS']::text[]),
  ('b2b software', ARRAY['Enterprise Software & SaaS']::text[]),
  ('b2b', ARRAY['Enterprise Software & SaaS']::text[]),
  ('software', ARRAY['Enterprise Software & SaaS']::text[]),
  ('b2b saas', ARRAY['Enterprise Software & SaaS']::text[]),
  ('b2b tech', ARRAY['Enterprise Software & SaaS']::text[]),
  ('b2b technology', ARRAY['Enterprise Software & SaaS']::text[]),
  ('enterprise saas', ARRAY['Enterprise Software & SaaS']::text[]),
  ('enterprise software', ARRAY['Enterprise Software & SaaS']::text[]),
  ('cloud', ARRAY['Enterprise Software & SaaS']::text[]),
  ('business applications', ARRAY['Enterprise Software & SaaS']::text[]),
  ('industrial software', ARRAY['Enterprise Software & SaaS']::text[]),
  ('vertical software', ARRAY['Enterprise Software & SaaS']::text[]),
  ('digital & tecnologia', ARRAY['Enterprise Software & SaaS']::text[]),
  ('digital', ARRAY['Enterprise Software & SaaS']::text[]),
  ('indústria & tecnologia', ARRAY['Enterprise Software & SaaS']::text[]),
  ('it', ARRAY['Enterprise Software & SaaS']::text[]),
  ('it/software/media', ARRAY['Enterprise Software & SaaS']::text[]),
  ('information technology', ARRAY['Enterprise Software & SaaS']::text[]),
  ('tech', ARRAY['Enterprise Software & SaaS']::text[]),
  ('technology', ARRAY['Enterprise Software & SaaS']::text[]),
  ('technical', ARRAY['Enterprise Software & SaaS']::text[]),
  ('software enabled hardware', ARRAY['Enterprise Software & SaaS']::text[]),
  ('dev tooling', ARRAY['Enterprise Software & SaaS']::text[]),
  ('open source', ARRAY['Enterprise Software & SaaS']::text[]),
  ('productivity', ARRAY['Enterprise Software & SaaS']::text[]),
  ('platform', ARRAY['Enterprise Software & SaaS']::text[]),
  ('platforms', ARRAY['Enterprise Software & SaaS']::text[]),
  ('compute stack', ARRAY['Enterprise Software & SaaS']::text[]),
  ('digitalization', ARRAY['Enterprise Software & SaaS']::text[]),
  ('digital tech', ARRAY['Enterprise Software & SaaS']::text[]),
  ('consumer tech', ARRAY['Enterprise Software & SaaS']::text[]),
  ('ai/ml', ARRAY['AI, Data & Analytics']::text[]),
  ('ai', ARRAY['AI, Data & Analytics']::text[]),
  ('artificial intelligence', ARRAY['AI, Data & Analytics']::text[]),
  ('ai tech', ARRAY['AI, Data & Analytics']::text[]),
  ('applied ai', ARRAY['AI, Data & Analytics']::text[]),
  ('ml', ARRAY['AI, Data & Analytics']::text[]),
  ('ai-native digitization', ARRAY['AI, Data & Analytics']::text[]),
  ('ai tech + infrastructure software', ARRAY['AI, Data & Analytics']::text[]),
  ('big data & ai', ARRAY['AI, Data & Analytics']::text[]),
  ('enterprise ai', ARRAY['AI, Data & Analytics']::text[]),
  ('enterprise automation & ai', ARRAY['AI, Data & Analytics']::text[]),
  ('data', ARRAY['AI, Data & Analytics']::text[]),
  ('data applications', ARRAY['AI, Data & Analytics']::text[]),
  ('data infrastructure', ARRAY['AI, Data & Analytics']::text[]),
  ('deep learning', ARRAY['AI, Data & Analytics']::text[]),
  ('next-gen computing', ARRAY['AI, Data & Analytics']::text[]),
  ('frontier tech', ARRAY['AI, Data & Analytics']::text[]),
  ('deep tech', ARRAY['DeepTech']::text[]),
  ('deeptech', ARRAY['DeepTech']::text[]),
  ('deep-tech', ARRAY['DeepTech']::text[]),
  ('science-based', ARRAY['DeepTech']::text[]),
  ('science-based deeptech', ARRAY['DeepTech']::text[]),
  ('science-based technologies (deep tech)', ARRAY['DeepTech']::text[]),
  ('science/digital', ARRAY['DeepTech']::text[]),
  ('critical technologies', ARRAY['DeepTech']::text[]),
  ('ip-rich', ARRAY['DeepTech']::text[]),
  ('physics', ARRAY['DeepTech']::text[]),
  ('mathematics', ARRAY['DeepTech']::text[]),
  ('consumer/consumer tech', ARRAY['Consumer Products & Services']::text[]),
  ('consumer', ARRAY['Consumer Products & Services']::text[]),
  ('dtc', ARRAY['Consumer Products & Services']::text[]),
  ('e-commerce', ARRAY['RetailTech & E-commerce']::text[]),
  ('grocery', ARRAY['Consumer Products & Services']::text[]),
  ('pets', ARRAY['Consumer Products & Services']::text[]),
  ('retail', ARRAY['Consumer Products & Services']::text[]),
  ('retail tech', ARRAY['RetailTech & E-commerce']::text[]),
  ('plant-based', ARRAY['Consumer Products & Services']::text[]),
  ('healthtech/biotech', ARRAY['Digital Health','Biotechnology & Life Sciences']::text[]),
  ('health and bio', ARRAY['Digital Health','Biotechnology & Life Sciences']::text[]),
  ('life sciences & health', ARRAY['Digital Health','Biotechnology & Life Sciences']::text[]),
  ('digital health', ARRAY['Digital Health']::text[]),
  ('health', ARRAY['Digital Health']::text[]),
  ('healthtech', ARRAY['Digital Health']::text[]),
  ('healthcare', ARRAY['Digital Health']::text[]),
  ('healthcare services', ARRAY['Digital Health']::text[]),
  ('patient platforms', ARRAY['Digital Health']::text[]),
  ('improving health for humanity', ARRAY['Digital Health']::text[]),
  ('personalized health', ARRAY['Digital Health']::text[]),
  ('taboo health', ARRAY['Digital Health']::text[]),
  ('data-driven health', ARRAY['Digital Health']::text[]),
  ('biotech', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('biotech/pharma', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('life science', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('life sciences', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('blue biotech', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('bioengineering', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('bioeconomy', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('biology', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('techbio', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('pharma', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('life sciences & chemistry', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('healthcare & life science', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('life sciences & care', ARRAY['Biotechnology & Life Sciences']::text[]),
  ('medtech', ARRAY['MedTech & Medical Devices']::text[]),
  ('med-tech', ARRAY['MedTech & Medical Devices']::text[]),
  ('medical devices', ARRAY['MedTech & Medical Devices']::text[]),
  ('medical technologies', ARRAY['MedTech & Medical Devices']::text[]),
  ('med tech & life sciences', ARRAY['MedTech & Medical Devices']::text[]),
  ('medtech & digital health', ARRAY['MedTech & Medical Devices']::text[]),
  ('deeptech healthcare', ARRAY['MedTech & Medical Devices']::text[]),
  ('diagnostics', ARRAY['Diagnostics']::text[]),
  ('tecnologias da saúde', ARRAY['Digital Health']::text[]),
  ('climate tech/cleantech', ARRAY['ClimateTech & CleanTech']::text[]),
  ('climate', ARRAY['ClimateTech & CleanTech']::text[]),
  ('cleantech', ARRAY['ClimateTech & CleanTech']::text[]),
  ('climate tech', ARRAY['ClimateTech & CleanTech']::text[]),
  ('climatetech', ARRAY['ClimateTech & CleanTech']::text[]),
  ('clean tech', ARRAY['ClimateTech & CleanTech']::text[]),
  ('climatech', ARRAY['ClimateTech & CleanTech']::text[]),
  ('clean tech & industrials', ARRAY['ClimateTech & CleanTech']::text[]),
  ('climate technologies', ARRAY['ClimateTech & CleanTech']::text[]),
  ('sustainability', ARRAY['ClimateTech & CleanTech']::text[]),
  ('sustainable innovation', ARRAY['ClimateTech & CleanTech']::text[]),
  ('green transition', ARRAY['ClimateTech & CleanTech']::text[]),
  ('circular economy', ARRAY['Circular Economy & Waste']::text[]),
  ('waste & circular economy', ARRAY['ClimateTech & CleanTech']::text[]),
  ('environmental services', ARRAY['ClimateTech & CleanTech']::text[]),
  ('energy', ARRAY['Energy & Energy Storage']::text[]),
  ('renewable energy', ARRAY['Energy & Energy Storage']::text[]),
  ('energy transition', ARRAY['Energy & Energy Storage']::text[]),
  ('energy storage', ARRAY['Energy & Energy Storage']::text[]),
  ('decentralised energy systems', ARRAY['Energy & Energy Storage']::text[]),
  ('sustainable energy', ARRAY['Energy & Energy Storage']::text[]),
  ('ocean renewable energy', ARRAY['Energy & Energy Storage']::text[]),
  ('energy & sustainability', ARRAY['Energy & Energy Storage']::text[]),
  ('electrification', ARRAY['Energy & Energy Storage']::text[]),
  ('green shipping', ARRAY['Energy & Energy Storage']::text[]),
  ('clean transport', ARRAY['Energy & Energy Storage']::text[]),
  ('circular economy (dup)', ARRAY['Circular Economy & Waste']::text[]),
  ('climate/ocean', ARRAY['BlueTech & OceanTech']::text[]),
  ('ocean security', ARRAY['BlueTech & OceanTech']::text[]),
  ('ocean-related startups', ARRAY['BlueTech & OceanTech']::text[]),
  ('sustainable ocean', ARRAY['BlueTech & OceanTech']::text[]),
  ('sustainable aquaculture', ARRAY['BlueTech & OceanTech']::text[]),
  ('sustainable fisheries', ARRAY['BlueTech & OceanTech']::text[]),
  ('aquaculture', ARRAY['BlueTech & OceanTech']::text[]),
  ('maritime operations', ARRAY['BlueTech & OceanTech']::text[]),
  ('shipbuilding & repair', ARRAY['BlueTech & OceanTech']::text[]),
  ('coastal tourism', ARRAY['BlueTech & OceanTech']::text[]),
  ('foodtech/agritech', ARRAY['AgriTech & FoodTech']::text[]),
  ('agriculture', ARRAY['AgriTech & FoodTech']::text[]),
  ('agritech', ARRAY['AgriTech & FoodTech']::text[]),
  ('agtech', ARRAY['AgriTech & FoodTech']::text[]),
  ('agrifoodtech', ARRAY['AgriTech & FoodTech']::text[]),
  ('agrifood-tech', ARRAY['AgriTech & FoodTech']::text[]),
  ('agrofood', ARRAY['AgriTech & FoodTech']::text[]),
  ('agri-industry', ARRAY['AgriTech & FoodTech']::text[]),
  ('foodtech', ARRAY['AgriTech & FoodTech']::text[]),
  ('food', ARRAY['AgriTech & FoodTech']::text[]),
  ('food systems', ARRAY['AgriTech & FoodTech']::text[]),
  ('sustainable agriculture', ARRAY['AgriTech & FoodTech']::text[]),
  ('fintech', ARRAY['FinTech & InsurTech']::text[]),
  ('insurtech', ARRAY['FinTech & InsurTech']::text[]),
  ('financial services', ARRAY['FinTech & InsurTech']::text[]),
  ('financial infrastructure', ARRAY['FinTech & InsurTech']::text[]),
  ('financial platforms', ARRAY['FinTech & InsurTech']::text[]),
  ('fintech infrastructure', ARRAY['FinTech & InsurTech']::text[]),
  ('insurance', ARRAY['FinTech & InsurTech']::text[]),
  ('currency technology', ARRAY['FinTech & InsurTech']::text[]),
  ('climate fintech', ARRAY['FinTech & InsurTech']::text[]),
  ('cybersecurity', ARRAY['Cybersecurity']::text[]),
  ('security', ARRAY['Cybersecurity']::text[]),
  ('securitytech', ARRAY['Cybersecurity']::text[]),
  ('digital security', ARRAY['Cybersecurity']::text[]),
  ('cyber-physical security', ARRAY['Cybersecurity']::text[]),
  ('ai & cybersecurity', ARRAY['Cybersecurity']::text[]),
  ('cybersecurity + defense tech', ARRAY['Cybersecurity']::text[]),
  ('defence', ARRAY['Defence & Dual-Use']::text[]),
  ('defense', ARRAY['Defence & Dual-Use']::text[]),
  ('sovereignty', ARRAY['Defence & Dual-Use']::text[]),
  ('hardware/robotics', ARRAY['Robotics & Automation']::text[]),
  ('hardware', ARRAY['Robotics & Automation']::text[]),
  ('hardware components', ARRAY['Robotics & Automation']::text[]),
  ('hardware/hightech', ARRAY['Robotics & Automation']::text[]),
  ('iot', ARRAY['Robotics & Automation']::text[]),
  ('iot/robotics', ARRAY['Robotics & Automation']::text[]),
  ('robotics', ARRAY['Robotics & Automation']::text[]),
  ('autonomous systems', ARRAY['Robotics & Automation']::text[]),
  ('autonomous systems & robotics', ARRAY['Robotics & Automation']::text[]),
  ('sensors', ARRAY['Robotics & Automation']::text[]),
  ('mems', ARRAY['Robotics & Automation']::text[]),
  ('wearables', ARRAY['Robotics & Automation']::text[]),
  ('augmented reality', ARRAY['Robotics & Automation']::text[]),
  ('additive manufacturing', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('advanced manufacturing', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('aerospace manufacturing', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrial', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrials', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrial automation', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrial tech', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industry tech', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrytech', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrial & enterprise solutions', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('industrial, climate & deep tech', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('infratech & mobility', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('high tech systems & materials', ARRAY['IndustrialTech & Advanced Manufacturing']::text[]),
  ('semiconductor', ARRAY['Semiconductors & Electronics']::text[]),
  ('semiconductors', ARRAY['Semiconductors & Electronics']::text[]),
  ('new materials + semiconductors', ARRAY['Semiconductors & Electronics']::text[]),
  ('electronics', ARRAY['Semiconductors & Electronics']::text[]),
  ('electronics & photonics', ARRAY['Semiconductors & Electronics']::text[]),
  ('materials science', ARRAY['Advanced Materials & Chemicals']::text[]),
  ('chemistry', ARRAY['Advanced Materials & Chemicals']::text[]),
  ('quantum', ARRAY['Advanced Materials & Chemicals']::text[]),
  ('quantum technologies', ARRAY['Advanced Materials & Chemicals']::text[]),
  ('space', ARRAY['Aerospace & SpaceTech']::text[]),
  ('space tech', ARRAY['Aerospace & SpaceTech']::text[]),
  ('spacetech', ARRAY['Aerospace & SpaceTech']::text[]),
  ('mobility/logistics', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('mobility', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('logistics', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('supply chain', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('supply chain tech', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('transportation', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('automotive', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('smart territories & mobility', ARRAY['Automotive, Mobility & Transportation','Logistics & Supply Chain']::text[]),
  ('built environment', ARRAY['ConstructionTech & Infrastructure']::text[]),
  ('data & connectivity', ARRAY['Telecommunications & Connectivity']::text[]),
  ('wireless technology', ARRAY['Telecommunications & Connectivity']::text[]),
  ('media/gaming', ARRAY['Gaming, Media & Entertainment']::text[]),
  ('media', ARRAY['Gaming, Media & Entertainment']::text[]),
  ('entertainment', ARRAY['Gaming, Media & Entertainment']::text[]),
  ('creative industries', ARRAY['Gaming, Media & Entertainment']::text[]),
  ('edtech', ARRAY['EdTech']::text[]),
  ('proptech', ARRAY['PropTech']::text[]),
  ('real estate', ARRAY['PropTech']::text[]),
  ('real assets', ARRAY['PropTech']::text[]),
  ('adtech', ARRAY['MarketingTech & AdTech']::text[]),
  ('turismo', ARRAY['TravelTech & Hospitality']::text[]),
  ('future of work', ARRAY['HRTech & Future of Work']::text[]),
  ('talent', ARRAY['HRTech & Future of Work']::text[]),
  ('regtech', ARRAY['LegalTech & RegTech']::text[]),
  ('education', ARRAY['EdTech']::text[]),
  ('digital infrastructure', ARRAY['Developer Tools & Cloud Infrastructure']::text[]),
  ('digital infrastructure (dup)', ARRAY['Developer Tools & Cloud Infrastructure']::text[]),
  ('inclusion', ARRAY['Social Impact & Financial Inclusion']::text[]),
  ('impact', ARRAY['Social Impact & Financial Inclusion']::text[]),
  ('impact investing', ARRAY['Social Impact & Financial Inclusion']::text[]),
  ('community and social enterprise', ARRAY['Social Impact & Financial Inclusion']::text[]),
  ('female founders', ARRAY['Social Impact & Financial Inclusion']::text[]),
  ('fashion & beauty', ARRAY['Fashion & Beauty']::text[]),
  ('sportstech', ARRAY['Sports, Fitness & Wellness']::text[]),
  ('generalist/sector-agnostic', ARRAY[]::text[]),
  ('generalist', ARRAY[]::text[]),
  ('generalist tech', ARRAY[]::text[]),
  ('generalist pe', ARRAY[]::text[]),
  ('generalist corporate vc', ARRAY[]::text[]),
  ('generalist early-stage', ARRAY[]::text[]),
  ('generalist syndicate', ARRAY[]::text[]),
  ('seed generalist', ARRAY[]::text[]),
  ('sme generalist', ARRAY[]::text[]),
  ('multi-sector', ARRAY[]::text[]),
  ('corporate vc generalist', ARRAY[]::text[]),
  ('corporate vc b2b saas', ARRAY[]::text[]),
  ('corporate vc cross-industry', ARRAY[]::text[]),
  ('corporate accelerator', ARRAY[]::text[]),
  ('venture capital', ARRAY[]::text[]),
  ('venture', ARRAY[]::text[]),
  ('venture studio', ARRAY[]::text[]),
  ('private equity', ARRAY[]::text[]),
  ('pe-vc', ARRAY[]::text[]),
  ('pe for startups', ARRAY[]::text[]),
  ('growth', ARRAY[]::text[]),
  ('growth equity', ARRAY[]::text[]),
  ('debt', ARRAY[]::text[]),
  ('private debt', ARRAY[]::text[]),
  ('equity', ARRAY[]::text[]),
  ('investing', ARRAY[]::text[]),
  ('investment', ARRAY[]::text[]),
  ('business investment', ARRAY[]::text[]),
  ('acquisitions', ARRAY[]::text[]),
  ('early-stage', ARRAY[]::text[]),
  ('early-stage businesses', ARRAY[]::text[]),
  ('early-stage companies', ARRAY[]::text[]),
  ('family office', ARRAY[]::text[]),
  ('eis', ARRAY[]::text[]),
  ('eis eligible ventures', ARRAY[]::text[]),
  ('seis eligible ventures', ARRAY[]::text[]),
  ('vct', ARRAY[]::text[]),
  ('export credit', ARRAY[]::text[]),
  ('risk', ARRAY[]::text[]),
  ('innovation', ARRAY[]::text[]),
  ('european startups', ARRAY[]::text[]),
  ('smbs', ARRAY[]::text[]),
  ('sme tech', ARRAY[]::text[]),
  ('start', ARRAY[]::text[]),
  ('pre-seed b2b', ARRAY[]::text[]),
  ('finance', ARRAY[]::text[]),
  ('financial services (dup)', ARRAY[]::text[]),
  ('professional services', ARRAY[]::text[]),
  ('marketplace', ARRAY['Consumer Products & Services']::text[]),
  ('infrastructure', ARRAY['Developer Tools & Cloud Infrastructure']::text[]),
  ('provider tools', ARRAY['Developer Tools & Cloud Infrastructure']::text[]),
  ('enterprise', ARRAY['Enterprise Software & SaaS']::text[]),
  ('nature', ARRAY['ClimateTech & CleanTech']::text[]),
  ('blockchain', ARRAY[]::text[]),
  ('health ventures', ARRAY[]::text[]),
  ('web3', ARRAY[]::text[])
)
update public.catalog_entities ce
set sectors_normalized = coalesce(agg.result, ARRAY[]::text[])
from (
  select ce2.id,
    (select array_agg(distinct s) from (
      select unnest(l.canonicos) as s
      from unnest(ce2.sectors) as raw_s
      join lookup l on l.valor_original = lower(btrim(raw_s))
    ) x) as result
  from public.catalog_entities ce2
) agg
where agg.id = ce.id;
