-- Prompt 444 §A/§B — Market Intelligence Phase 1 foundation: Market Thesis
-- replaces the "market_terms" concept, and 2-3 market hypotheses replace a
-- single assumed truth. Fixes the confirmed bug where market research was
-- grounded on sectors.join(', ') (proposing Cleanwatts/Agroop as
-- competitors for a health biochip) by giving research something real —
-- what the platform actually knows about the company — to search from.

-- org_market_thesis: one row per org (upsert, no history — same discipline
-- as org_market_data, migration 0241). version increments only when a
-- content field changes (never on a cosmetic/no-op save) — phase 448
-- ("What we learned") compares "since the last revision" against it rather
-- than "since forever".
create table if not exists org_market_thesis (
  org_id uuid primary key references orgs(id) on delete cascade,
  product_summary text,          -- what the company does, in the founder's own words
  core_problem text,
  primary_user text,             -- who uses it
  economic_buyer text,           -- who pays/decides
  beachhead text,                -- first segment to attack
  geography text,
  primary_use_case text,
  adjacent_technologies text[] not null default '{}',
  excluded_markets text[] not null default '{}',  -- "we are not X, don't compare us to Y"
  version int not null default 1,
  updated_at timestamptz not null default now(),
  check (product_summary is null or char_length(product_summary) <= 300),
  check (core_problem is null or char_length(core_problem) <= 300),
  check (primary_user is null or char_length(primary_user) <= 300),
  check (economic_buyer is null or char_length(economic_buyer) <= 300),
  check (beachhead is null or char_length(beachhead) <= 300),
  check (geography is null or char_length(geography) <= 300),
  check (primary_use_case is null or char_length(primary_use_case) <= 300),
  check (array_length(adjacent_technologies, 1) is null or array_length(adjacent_technologies, 1) <= 8),
  check (array_length(excluded_markets, 1) is null or array_length(excluded_markets, 1) <= 8)
);

alter table org_market_thesis enable row level security;

drop policy if exists org_market_thesis_org_members on org_market_thesis;
create policy org_market_thesis_org_members on org_market_thesis
  for all using (is_org_member(org_id)) with check (is_org_member(org_id));

comment on table org_market_thesis is
  'Prompt 444 §A — founder-declared Market Thesis: what the platform actually knows about the company, grounding every market search from here on instead of raw sector tags. One row per org, always current (no history); version increments on content change only.';

-- org_market_hypotheses: 2-3 alternative readings of the same product, not
-- one assumed truth. Generated by /api/market-thesis/hypotheses/generate
-- (verify-then-promote — never written directly by that route, only by the
-- founder's explicit confirmation) or hand-written by the founder.
-- Hard cap of 3 'active' per org, enforced server-side (§B) — this is
-- about intellectual focus, not just cost, so it's a deliberate ceiling,
-- not a soft warning. 'archived' never counts against the cap and a
-- hypothesis is never deleted, same "if it exists it's authentic" rule
-- this codebase applies everywhere else.
create table if not exists org_market_hypotheses (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references orgs(id) on delete cascade,
  label text not null,
  definition text not null,
  thesis_version int not null,   -- the org_market_thesis.version that generated (or was current for) this hypothesis
  status text not null default 'active' check (status in ('active', 'archived')),
  position int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(label) > 0),
  check (char_length(definition) > 0)
);

create index if not exists org_market_hypotheses_org_idx on org_market_hypotheses(org_id, status);

alter table org_market_hypotheses enable row level security;

drop policy if exists org_market_hypotheses_org_members on org_market_hypotheses;
create policy org_market_hypotheses_org_members on org_market_hypotheses
  for all using (is_org_member(org_id)) with check (is_org_member(org_id));

comment on table org_market_hypotheses is
  'Prompt 444 §B — 2-3 alternative market readings per org, never a single assumed truth. Max 3 active per org (app-enforced); archived, never deleted.';
